variables:
    DOCKER_TAG_DEV: ${CI_COMMIT_REF_NAME}
    DOCKER_IMAGE_DEV: cimpy
  
stages:
- prepare
- generate

docker:
    stage: prepare
    script:
        - docker build -t ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV} .
    tags:
        - shell
        - linux


documentation:
    stage: generate
    script:
        - cd scripts && ./docu.sh
    image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
    artifacts:
        paths:
            - documentation
    tags:
        - docker

test:pytest:
    stage: test
    variables:
        PYTHONPATH: "build/Source/Python:Source/Python"
    script:
        - pytest -v tests
    image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
    tags:
        - docker