variables:
    DOCKER_TAG_DEV: ${CI_COMMIT_REF_NAME}
    DOCKER_IMAGE_DEV: cimpy

stages:
- prepare
- generate
- test-import
- test-export-with-imported-files
- test-export-with-exported-files


docker:
    stage: prepare
    script:
        - docker build -t ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV} .
    tags:
        - shell
        - linux


documentation:
    stage: generate
    script:
        - cd scripts && ./docu.sh
    image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
    artifacts:
        paths:
            - documentation
    tags:
        - docker

test:import:
    stage: test-import
    variables:
        PYTHONPATH: "build/Source/Python:Source/Python"
    script:
        - python3 setup.py develop
        - cd tests && pytest -v test_import.py
    image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
    tags:
        - docker

test:export-with-imported-files:
    stage: test-export-with-imported-files
    variables:
        PYTHONPATH: "build/Source/Python:Source/Python"
    script:
        - python3 setup.py develop
        - cd tests && pytest -v test_export_with_imported_files.py
    image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
    tags:
        - docker

test:export-export:
    stage: test-export-with-exported-files
    variables:
        PYTHONPATH: "build/Source/Python:Source/Python"
    script:
        - python3 setup.py develop
        - cd tests && pytest -v test_export_with_exported_files.py
    image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
    tags:
        - docker