variables:
    DOCKER_TAG_DEV: ${CI_COMMIT_REF_NAME}
    DOCKER_IMAGE_DEV: cimpy
    DOCKER_FILE: ${CI_PROJECT_DIR}/Dockerfile

stages:
- prepare
- test
- generate
- deploy


prepare:
  variables:
    GIT_SUBMODULE_STRATEGY: none
  stage: prepare
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile ${DOCKER_FILE} --destination ${CI_REGISTRY_IMAGE}:${DOCKER_IMAGE_DEV}-base-image --cache=true --snapshotMode=redo --use-new-run


text-documentation:
    stage: generate
    script:
        - cd documentation && ./docu.sh
    image: ${CI_REGISTRY_IMAGE}:${DOCKER_IMAGE_DEV}-base-image
    except:
        - master
    needs: ['prepare']

html-documentation:
    stage: generate
    script:
        - cd documentation && ./docu.sh --release
    image: ${CI_REGISTRY_IMAGE}:${DOCKER_IMAGE_DEV}-base-image
    artifacts:
        paths:
            - documentation
    only:
        - master
    needs: ['prepare']


pages:
    stage: deploy
    script:
        - mkdir .public
        - cp -r documentation/_build/html/. .public
        - mv .public public
    artifacts:
        paths:
            - public
            - .public
    dependencies:
        - html-documentation
    only:
        - master
    needs: ['html-documentation']

test:
    stage: test
    variables:
        PYTHONPATH: "build/Source/Python:Source/Python"
    script:
        - pytest -v -cov --junitxml=report.xml
    image: ${CI_REGISTRY_IMAGE}:${DOCKER_IMAGE_DEV}-base-image

    artifacts:
        reports:
            junit: report.xml
    needs: ['prepare']
